pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/sagarrajak245/interntask.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('docker_exp') { // Correct directory name from your filesystem
                    bat 'dir' // Windows equivalent of ls -l
                    bat 'docker build -t my-docker-webapp .' // Build Docker Image
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                bat 'docker stop my-docker-webapp || exit 0' // Stop existing container if it exists
                bat 'docker rm my-docker-webapp || exit 0' // Remove existing container if it exists
                bat 'docker run -d -p 8081:80 --name my-docker-webapp my-docker-webapp'
            }
        }
    }
}